export const ARENA_RULES_VERSION="1.1";
export const STRATEGY_INTEGRATION_VERSION="1.0.0";
export const ALLOWED_ACTIONS=Object.freeze(["TRADE","PASS","SELL","MANAGE_POSITION"]);
export const CANDIDATE_SOURCES=Object.freeze(["RAFI_OPPORTUNITY","LIVE_MOVER","CORE_ASSET"]);
export const REASON_CODES=Object.freeze({
 VIVIAN_HIGH_CONVICTION_ENTRY:"Vivian high-conviction entry",VIVIAN_VALID_ENTRY:"Vivian valid entry",VIVIAN_CAUTIOUS_ENTRY:"Vivian cautious entry",VIVIAN_HARD_STOP:"Vivian hard stop",VIVIAN_THESIS_INVALIDATED:"Vivian thesis invalidated",VIVIAN_PROFIT_TARGET:"Vivian profit target",VIVIAN_PROFIT_PROTECTION:"Vivian profit protection",VIVIAN_TIME_EXIT:"Vivian time exit",VIVIAN_ROUND_EXIT:"Vivian round exit",VIVIAN_STALE_QUOTE:"Vivian stale quote",VIVIAN_COST_REJECTION:"Vivian cost rejection",VIVIAN_WEAK_SETUP:"Vivian weak setup",VIVIAN_NO_OPPORTUNITY:"Vivian no opportunity",VIVIAN_MONITOR_POSITION:"Vivian position monitoring",VIVIAN_PORTFOLIO_FULL:"Vivian portfolio full",VIVIAN_INSUFFICIENT_CASH:"Vivian insufficient cash",
 ATLAS_RISK_EXIT:"Preston risk limit reached",ATLAS_ROUND_PRESSURE:"Preston round-end exit",ATLAS_REVERSION_TARGET:"Preston profit target reached",ATLAS_HALFTIME_VALUE_ENTRY:"Preston halftime value entry",ATLAS_REVERSION_ENTRY:"Preston reversion entry",ATLAS_MONITOR_PORTFOLIO:"Preston portfolio unchanged",ATLAS_NO_OVERSOLD_ASSET:"No qualifying oversold asset",ATLAS_PORTFOLIO_FULL:"Preston has no available slot"
 ,ENTRY_STRONG_EVIDENCE:"Preston strong-evidence entry",ENTRY_RISK_ADJUSTED:"Preston risk-adjusted entry",PASS_NO_ELIGIBLE_OPPORTUNITY:"Preston found no eligible opportunity",PASS_WEAK_EVIDENCE:"Preston rejected weak evidence",PASS_LATE_ENTRY:"Preston rejected an extended move",PASS_INVALID_CONTEXT:"Preston rejected invalid context",HOLD_THESIS_INTACT:"Preston thesis remains intact",EXIT_TAKE_PROFIT:"Preston take-profit exit",EXIT_STOP_LOSS:"Preston stop-loss exit",EXIT_ROUND_END:"Preston round-end exit",EXIT_THESIS_BROKEN:"Preston thesis-broken exit"
});
export function validateStrategyContext(context){if(!context||typeof context!=="object")throw new Error("Strategy context is required");if(!context.agent||!Array.isArray(context.candidates)||!context.assets||!context.round||!context.campaign)throw new Error("Strategy context is incomplete");if(!Number.isInteger(context.availableSlots)||context.availableSlots<0||context.availableSlots>3)throw new Error("availableSlots must be an integer from zero through three");return context;}
export function validateStrategyDecision(d){if(!d||!ALLOWED_ACTIONS.includes(d.decision))throw new Error("Invalid agent decision");if(d.decision==="TRADE"&&(!d.selectedCandidateId||!d.productId||d.allocation?.type!=="PERCENT_OF_AVAILABLE_CASH"||!Number.isFinite(d.allocation.value)||d.allocation.value<1||d.allocation.value>100))throw new Error("Invalid trade decision");if(d.decision!=="TRADE"&&d.allocation!==null)throw new Error("Non-trade allocation must be null");if(d.decision==="SELL"&&(!d.productId||!Number.isFinite(d.positionPercent)))throw new Error("Invalid sell decision");return d;}
