export const ARENA_RULES_VERSION="1.1";
export const STRATEGY_INTEGRATION_VERSION="1.0.0";
export const ALLOWED_ACTIONS=Object.freeze(["TRADE","PASS","SELL","MANAGE_POSITION"]);
export const CANDIDATE_SOURCES=Object.freeze(["RAFI_OPPORTUNITY","LIVE_MOVER","CORE_ASSET"]);
export const REASON_CODES=Object.freeze({
 CODY_RISK_EXIT:"Vivian risk limit reached",CODY_ROUND_PRESSURE:"Vivian round-end exit",CODY_MOMENTUM_TARGET:"Vivian profit target reached",CODY_EXPANDED_SEARCH_ENTRY:"Vivian halftime entry",CODY_MOMENTUM_ENTRY:"Vivian momentum entry",CODY_MONITOR_PORTFOLIO:"Vivian portfolio unchanged",CODY_NO_POSITIVE_MOMENTUM:"No qualifying positive momentum",CODY_PORTFOLIO_FULL:"Vivian has no available slot",
 ATLAS_RISK_EXIT:"Preston risk limit reached",ATLAS_ROUND_PRESSURE:"Preston round-end exit",ATLAS_REVERSION_TARGET:"Preston profit target reached",ATLAS_HALFTIME_VALUE_ENTRY:"Preston halftime value entry",ATLAS_REVERSION_ENTRY:"Preston reversion entry",ATLAS_MONITOR_PORTFOLIO:"Preston portfolio unchanged",ATLAS_NO_OVERSOLD_ASSET:"No qualifying oversold asset",ATLAS_PORTFOLIO_FULL:"Preston has no available slot"
});
export function validateStrategyContext(context){if(!context||typeof context!=="object")throw new Error("Strategy context is required");if(!context.agent||!Array.isArray(context.candidates)||!context.assets||!context.round||!context.campaign)throw new Error("Strategy context is incomplete");if(!Number.isInteger(context.availableSlots)||context.availableSlots<0||context.availableSlots>3)throw new Error("availableSlots must be an integer from zero through three");return context;}
export function validateStrategyDecision(d){if(!d||!ALLOWED_ACTIONS.includes(d.decision))throw new Error("Invalid agent decision");if(d.decision==="TRADE"&&(!d.selectedCandidateId||!d.productId||d.allocation?.type!=="PERCENT_OF_AVAILABLE_CASH"||!Number.isFinite(d.allocation.value)||d.allocation.value<1||d.allocation.value>100))throw new Error("Invalid trade decision");if(d.decision!=="TRADE"&&d.allocation!==null)throw new Error("Non-trade allocation must be null");if(d.decision==="SELL"&&(!d.productId||!Number.isFinite(d.positionPercent)))throw new Error("Invalid sell decision");return d;}
